name: qr_code_manager_qr_home
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"
resolution: workspace

dependencies:
  cupertino_icons: ^1.0.8
  drift_flutter: ^0.2.4
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_modular: ^6.3.4
  flutter_secure_storage: ^9.2.4
  oxidized: ^6.2.0
  url_launcher: ^6.3.1

dev_dependencies:
  build_runner: ^2.4.15
  drift_dev: ^2.25.2
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^7.0.0


flutter: